### ISSUE TITLE
Automated build on docker hub fails

### ISSUE THREAD

**Issue by julianxhokaxhiu** [finalduty/docker-archlinux#1]
Hi,

may I ask if you have any idea why I am getting this weirdo errors lately using your base image?

```
/usr/share/makepkg/util/pkgbuild.sh: line 29: /dev/null: Permission denied
/usr/share/makepkg/util/pkgbuild.sh: line 69: /dev/fd/62: Permission denied
```

It seems something changed on their side ( or somethng is broken on the base image ) that stopped to work 7 days ago ( see https://hub.docker.com/r/julianxhokaxhiu/docker-lineage-cicd/builds/ ).

Any help is really appreciated.

Best regards,
Julian

**Comment by finalduty** [comment]
Hi Julian,

This looks to be due to the permissions used when using you're running the `apacman` install. As best as I know, packages from the AUR can't be run as root and in this instance are built using the 'aurbuild' user. This user does not have access to the requires areas of the file system by default, as noticed in your error messages.

This may not be the most secure method, but I suggest adding the following to your Dockerfile before you call `apacman`:
```
usermod -G root aurbuild
```

This will add the aurbuild user to the root group, which when I tested, allowed apacman to execute. There was however a further issue with the PGP signatures for the build which I can't help you with at this time.

Hope this helps :)

Andy
